// Comprehensive mission database with 250+ actions across all categories and difficulty levels

export const missionTiers = {
  beginner: {
    name: 'First Steps',
    unlocked: true,
    requiredActs: 0,
    missions: [
      // SERVICE - Beginner (10 missions)
      { id: 'b_svc_1', category: 'service', text: 'Hold the door for someone without waiting for thanks', difficulty: 'gentle' },
      { id: 'b_svc_2', category: 'service', text: 'Pick up litter you didn\'t drop', difficulty: 'gentle' },
      { id: 'b_svc_3', category: 'service', text: 'Let someone merge in traffic without acknowledgment', difficulty: 'gentle' },
      { id: 'b_svc_4', category: 'service', text: 'Return a shopping cart for someone', difficulty: 'gentle' },
      { id: 'b_svc_5', category: 'service', text: 'Smile genuinely at a stranger', difficulty: 'gentle' },
      { id: 'b_svc_6', category: 'service', text: 'Leave a filled parking meter for the next person', difficulty: 'gentle' },
      { id: 'b_svc_7', category: 'service', text: 'Water a neglected plant in a public space', difficulty: 'gentle' },
      { id: 'b_svc_8', category: 'service', text: 'Straighten items on a store shelf', difficulty: 'gentle' },
      { id: 'b_svc_9', category: 'service', text: 'Give up your seat without being asked', difficulty: 'gentle' },
      { id: 'b_svc_10', category: 'service', text: 'Help someone reach something high', difficulty: 'gentle' },

      // RESTRAINT - Beginner (10 missions)
      { id: 'b_rst_1', category: 'restraint', text: 'Listen to someone fully without interrupting', difficulty: 'gentle' },
      { id: 'b_rst_2', category: 'restraint', text: 'Let someone have the last word in a minor disagreement', difficulty: 'gentle' },
      { id: 'b_rst_3', category: 'restraint', text: 'Don\'t check your phone for one full hour', difficulty: 'gentle' },
      { id: 'b_rst_4', category: 'restraint', text: 'Skip complaining about something minor today', difficulty: 'gentle' },
      { id: 'b_rst_5', category: 'restraint', text: 'Resist the urge to correct someone on a trivial matter', difficulty: 'gentle' },
      { id: 'b_rst_6', category: 'restraint', text: 'Don\'t gossip when given the opportunity', difficulty: 'gentle' },
      { id: 'b_rst_7', category: 'restraint', text: 'Pause before responding when annoyed', difficulty: 'gentle' },
      { id: 'b_rst_8', category: 'restraint', text: 'Skip one indulgent purchase you were considering', difficulty: 'gentle' },
      { id: 'b_rst_9', category: 'restraint', text: 'Don\'t defend yourself when lightly criticized', difficulty: 'gentle' },
      { id: 'b_rst_10', category: 'restraint', text: 'Refrain from sharing an opinion no one asked for', difficulty: 'gentle' },

      // DISCIPLINE - Beginner (10 missions)
      { id: 'b_dis_1', category: 'discipline', text: 'Tidy a small space that brings you peace', difficulty: 'gentle' },
      { id: 'b_dis_2', category: 'discipline', text: 'Do one task you\'ve been postponing', difficulty: 'gentle' },
      { id: 'b_dis_3', category: 'discipline', text: 'Wake up 10 minutes earlier than usual', difficulty: 'gentle' },
      { id: 'b_dis_4', category: 'discipline', text: 'Drink water instead of a sweet beverage once', difficulty: 'gentle' },
      { id: 'b_dis_5', category: 'discipline', text: 'Take the stairs instead of the elevator', difficulty: 'gentle' },
      { id: 'b_dis_6', category: 'discipline', text: 'Read for 15 minutes instead of scrolling', difficulty: 'gentle' },
      { id: 'b_dis_7', category: 'discipline', text: 'Make your bed mindfully', difficulty: 'gentle' },
      { id: 'b_dis_8', category: 'discipline', text: 'Prepare tomorrow\'s clothes tonight', difficulty: 'gentle' },
      { id: 'b_dis_9', category: 'discipline', text: 'Wash dishes right after using them', difficulty: 'gentle' },
      { id: 'b_dis_10', category: 'discipline', text: 'Spend 10 minutes in complete silence', difficulty: 'gentle' },

      // COURAGE - Beginner (10 missions)
      { id: 'b_crg_1', category: 'courage', text: 'Say no to something you don\'t want to do', difficulty: 'gentle' },
      { id: 'b_crg_2', category: 'courage', text: 'Admit you don\'t know something', difficulty: 'gentle' },
      { id: 'b_crg_3', category: 'courage', text: 'Ask for help with something small', difficulty: 'gentle' },
      { id: 'b_crg_4', category: 'courage', text: 'Speak up when you notice an error', difficulty: 'gentle' },
      { id: 'b_crg_5', category: 'courage', text: 'Try something slightly outside your comfort zone', difficulty: 'gentle' },
      { id: 'b_crg_6', category: 'courage', text: 'Make eye contact when speaking', difficulty: 'gentle' },
      { id: 'b_crg_7', category: 'courage', text: 'Share an unpopular but harmless preference', difficulty: 'gentle' },
      { id: 'b_crg_8', category: 'courage', text: 'Eat alone in a public place', difficulty: 'gentle' },
      { id: 'b_crg_9', category: 'courage', text: 'Start a conversation with someone new', difficulty: 'gentle' },
      { id: 'b_crg_10', category: 'courage', text: 'Politely stand your ground on a minor matter', difficulty: 'gentle' },

      // MERCY - Beginner (10 missions)
      { id: 'b_mrc_1', category: 'mercy', text: 'Forgive yourself for a small mistake', difficulty: 'gentle' },
      { id: 'b_mrc_2', category: 'mercy', text: 'Let go of irritation toward someone', difficulty: 'gentle' },
      { id: 'b_mrc_3', category: 'mercy', text: 'Give someone the benefit of the doubt', difficulty: 'gentle' },
      { id: 'b_mrc_4', category: 'mercy', text: 'Show patience with a slow clerk or driver', difficulty: 'gentle' },
      { id: 'b_mrc_5', category: 'mercy', text: 'Think a kind thought about someone who annoyed you', difficulty: 'gentle' },
      { id: 'b_mrc_6', category: 'mercy', text: 'Overlook a minor offense', difficulty: 'gentle' },
      { id: 'b_mrc_7', category: 'mercy', text: 'Refrain from judging someone\'s appearance', difficulty: 'gentle' },
      { id: 'b_mrc_8', category: 'mercy', text: 'Assume good intentions in a confusing interaction', difficulty: 'gentle' },
      { id: 'b_mrc_9', category: 'mercy', text: 'Be gentle with yourself about an imperfection', difficulty: 'gentle' },
      { id: 'b_mrc_10', category: 'mercy', text: 'Choose understanding over being right', difficulty: 'gentle' },

      // BENEVOLENCE - Beginner (10 missions)
      { id: 'b_bnv_1', category: 'benevolence', text: 'Leave a kind note for someone to find', difficulty: 'gentle' },
      { id: 'b_bnv_2', category: 'benevolence', text: 'Give a sincere compliment without expecting response', difficulty: 'gentle' },
      { id: 'b_bnv_3', category: 'benevolence', text: 'Share your umbrella with someone in the rain', difficulty: 'gentle' },
      { id: 'b_bnv_4', category: 'benevolence', text: 'Pay for someone\'s coffee behind you in line', difficulty: 'gentle' },
      { id: 'b_bnv_5', category: 'benevolence', text: 'Leave coins at a vending machine', difficulty: 'gentle' },
      { id: 'b_bnv_6', category: 'benevolence', text: 'Give away a book you enjoyed', difficulty: 'gentle' },
      { id: 'b_bnv_7', category: 'benevolence', text: 'Bring in someone\'s trash bin from the curb', difficulty: 'gentle' },
      { id: 'b_bnv_8', category: 'benevolence', text: 'Leave extra time on a parking meter', difficulty: 'gentle' },
      { id: 'b_bnv_9', category: 'benevolence', text: 'Share your snack with someone', difficulty: 'gentle' },
      { id: 'b_bnv_10', category: 'benevolence', text: 'Offer directions to someone who looks lost', difficulty: 'gentle' }
    ]
  },

  apprentice: {
    name: 'Quiet Practice',
    unlocked: false,
    requiredActs: 5,
    missions: [
      // SERVICE - Apprentice (10 missions)
      { id: 'a_svc_1', category: 'service', text: 'Clean something that isn\'t yours without acknowledgment', difficulty: 'modest' },
      { id: 'a_svc_2', category: 'service', text: 'Anonymously do someone\'s chore', difficulty: 'modest' },
      { id: 'a_svc_3', category: 'service', text: 'Fix something broken in a public space', difficulty: 'modest' },
      { id: 'a_svc_4', category: 'service', text: 'Organize a shared space no one asked you to', difficulty: 'modest' },
      { id: 'a_svc_5', category: 'service', text: 'Shovel or sweep for a neighbor anonymously', difficulty: 'modest' },
      { id: 'a_svc_6', category: 'service', text: 'Leave helpful supplies somewhere they\'re needed', difficulty: 'modest' },
      { id: 'a_svc_7', category: 'service', text: 'Quietly cover someone\'s shift or responsibility', difficulty: 'modest' },
      { id: 'a_svc_8', category: 'service', text: 'Repair something without telling anyone', difficulty: 'modest' },
      { id: 'a_svc_9', category: 'service', text: 'Stock or refill something that\'s running low', difficulty: 'modest' },
      { id: 'a_svc_10', category: 'service', text: 'Do the least desirable task in a group project', difficulty: 'modest' },

      // RESTRAINT - Apprentice (10 missions)
      { id: 'a_rst_1', category: 'restraint', text: 'Refrain from a response you feel justified in making', difficulty: 'modest' },
      { id: 'a_rst_2', category: 'restraint', text: 'Let someone believe they won an argument', difficulty: 'modest' },
      { id: 'a_rst_3', category: 'restraint', text: 'Don\'t share exciting personal news for 24 hours', difficulty: 'modest' },
      { id: 'a_rst_4', category: 'restraint', text: 'Keep a meaningful secret without mentioning you kept it', difficulty: 'modest' },
      { id: 'a_rst_5', category: 'restraint', text: 'Resist correcting misinformation that doesn\'t matter', difficulty: 'modest' },
      { id: 'a_rst_6', category: 'restraint', text: 'Skip social media for an entire day', difficulty: 'modest' },
      { id: 'a_rst_7', category: 'restraint', text: 'Don\'t explain yourself when misunderstood', difficulty: 'modest' },
      { id: 'a_rst_8', category: 'restraint', text: 'Hold your tongue when you have perfect comeback', difficulty: 'modest' },
      { id: 'a_rst_9', category: 'restraint', text: 'Accept blame for something partly someone else\'s fault', difficulty: 'modest' },
      { id: 'a_rst_10', category: 'restraint', text: 'Don\'t seek credit for good work you did', difficulty: 'modest' },

      // DISCIPLINE - Apprentice (10 missions)
      { id: 'a_dis_1', category: 'discipline', text: 'Complete a task you\'ve been avoiding, in silence', difficulty: 'modest' },
      { id: 'a_dis_2', category: 'discipline', text: 'Exercise for 20 minutes without tracking it', difficulty: 'modest' },
      { id: 'a_dis_3', category: 'discipline', text: 'Cook a healthy meal instead of ordering out', difficulty: 'modest' },
      { id: 'a_dis_4', category: 'discipline', text: 'Go to bed 30 minutes earlier than usual', difficulty: 'modest' },
      { id: 'a_dis_5', category: 'discipline', text: 'Finish reading a challenging article or chapter', difficulty: 'modest' },
      { id: 'a_dis_6', category: 'discipline', text: 'Organize one cluttered area completely', difficulty: 'modest' },
      { id: 'a_dis_7', category: 'discipline', text: 'Practice a skill for 30 minutes privately', difficulty: 'modest' },
      { id: 'a_dis_8', category: 'discipline', text: 'Fast from one comfort food for the day', difficulty: 'modest' },
      { id: 'a_dis_9', category: 'discipline', text: 'Meditate or sit in silence for 15 minutes', difficulty: 'modest' },
      { id: 'a_dis_10', category: 'discipline', text: 'Complete a project you started and abandoned', difficulty: 'modest' },

      // COURAGE - Apprentice (10 missions)
      { id: 'a_crg_1', category: 'courage', text: 'Apologize without justifying your actions', difficulty: 'modest' },
      { id: 'a_crg_2', category: 'courage', text: 'Admit you were wrong about something', difficulty: 'modest' },
      { id: 'a_crg_3', category: 'courage', text: 'Do something alone you\'d usually do with others', difficulty: 'modest' },
      { id: 'a_crg_4', category: 'courage', text: 'Speak up against casual unkindness', difficulty: 'modest' },
      { id: 'a_crg_5', category: 'courage', text: 'Have a difficult conversation you\'ve been avoiding', difficulty: 'modest' },
      { id: 'a_crg_6', category: 'courage', text: 'Share a fear with someone you trust', difficulty: 'modest' },
      { id: 'a_crg_7', category: 'courage', text: 'Set a boundary with someone who expects too much', difficulty: 'modest' },
      { id: 'a_crg_8', category: 'courage', text: 'Try a new activity where you\'ll be a beginner', difficulty: 'modest' },
      { id: 'a_crg_9', category: 'courage', text: 'Ask someone for honest feedback', difficulty: 'modest' },
      { id: 'a_crg_10', category: 'courage', text: 'Decline a social obligation without a detailed excuse', difficulty: 'modest' },

      // MERCY - Apprentice (10 missions)
      { id: 'a_mrc_1', category: 'mercy', text: 'Show patience when you could be irritated', difficulty: 'modest' },
      { id: 'a_mrc_2', category: 'mercy', text: 'Forgive someone who doesn\'t know they hurt you', difficulty: 'modest' },
      { id: 'a_mrc_3', category: 'mercy', text: 'Let go of a grudge you\'ve been holding', difficulty: 'modest' },
      { id: 'a_mrc_4', category: 'mercy', text: 'Give grace to someone who disappointed you', difficulty: 'modest' },
      { id: 'a_mrc_5', category: 'mercy', text: 'Stop mentally rehearsing someone\'s wrongs', difficulty: 'modest' },
      { id: 'a_mrc_6', category: 'mercy', text: 'Extend compassion to someone you find difficult', difficulty: 'modest' },
      { id: 'a_mrc_7', category: 'mercy', text: 'Choose mercy over proving your point', difficulty: 'modest' },
      { id: 'a_mrc_8', category: 'mercy', text: 'Be gentle with someone who is struggling', difficulty: 'modest' },
      { id: 'a_mrc_9', category: 'mercy', text: 'Release yourself from shame about something past', difficulty: 'modest' },
      { id: 'a_mrc_10', category: 'mercy', text: 'Pray or wish well for someone who wronged you', difficulty: 'modest' },

      // BENEVOLENCE - Apprentice (10 missions)
      { id: 'a_bnv_1', category: 'benevolence', text: 'Leave a generous tip without being seen', difficulty: 'modest' },
      { id: 'a_bnv_2', category: 'benevolence', text: 'Mail an anonymous gift to someone', difficulty: 'modest' },
      { id: 'a_bnv_3', category: 'benevolence', text: 'Pay for someone\'s groceries behind you', difficulty: 'modest' },
      { id: 'a_bnv_4', category: 'benevolence', text: 'Leave money in a library book', difficulty: 'modest' },
      { id: 'a_bnv_5', category: 'benevolence', text: 'Donate items you love, not just old things', difficulty: 'modest' },
      { id: 'a_bnv_6', category: 'benevolence', text: 'Give flowers to a stranger', difficulty: 'modest' },
      { id: 'a_bnv_7', category: 'benevolence', text: 'Buy and distribute cold water on a hot day', difficulty: 'modest' },
      { id: 'a_bnv_8', category: 'benevolence', text: 'Leave a care package for your mail carrier', difficulty: 'modest' },
      { id: 'a_bnv_9', category: 'benevolence', text: 'Secretly pay off someone\'s small debt', difficulty: 'modest' },
      { id: 'a_bnv_10', category: 'benevolence', text: 'Give a meaningful gift disguised as if found', difficulty: 'modest' }
    ]
  },

  devoted: {
    name: 'Deepening Path',
    unlocked: false,
    requiredActs: 15,
    missions: [
      // SERVICE - Devoted (10 missions)
      { id: 'd_svc_1', category: 'service', text: 'Help someone who will never know it was you', difficulty: 'earnest' },
      { id: 'd_svc_2', category: 'service', text: 'Take on significant work without recognition', difficulty: 'earnest' },
      { id: 'd_svc_3', category: 'service', text: 'Create something useful and leave it anonymously', difficulty: 'earnest' },
      { id: 'd_svc_4', category: 'service', text: 'Volunteer time without telling anyone', difficulty: 'earnest' },
      { id: 'd_svc_5', category: 'service', text: 'Solve a problem for someone without them knowing', difficulty: 'earnest' },
      { id: 'd_svc_6', category: 'service', text: 'Complete someone\'s difficult task in secret', difficulty: 'earnest' },
      { id: 'd_svc_7', category: 'service', text: 'Maintain something for the community invisibly', difficulty: 'earnest' },
      { id: 'd_svc_8', category: 'service', text: 'Teach someone something valuable without credit', difficulty: 'earnest' },
      { id: 'd_svc_9', category: 'service', text: 'Serve in a way that costs you comfort', difficulty: 'earnest' },
      { id: 'd_svc_10', category: 'service', text: 'Give hours of your time with no acknowledgment', difficulty: 'earnest' },

      // RESTRAINT - Devoted (10 missions)
      { id: 'd_rst_1', category: 'restraint', text: 'Do not correct someone even though you know you\'re right', difficulty: 'earnest' },
      { id: 'd_rst_2', category: 'restraint', text: 'Keep silent about an achievement for a week', difficulty: 'earnest' },
      { id: 'd_rst_3', category: 'restraint', text: 'Let someone take credit for your idea', difficulty: 'earnest' },
      { id: 'd_rst_4', category: 'restraint', text: 'Resist all urges to self-promote for 48 hours', difficulty: 'earnest' },
      { id: 'd_rst_5', category: 'restraint', text: 'Don\'t defend your reputation when attacked', difficulty: 'earnest' },
      { id: 'd_rst_6', category: 'restraint', text: 'Fast from all unnecessary speaking for a day', difficulty: 'earnest' },
      { id: 'd_rst_7', category: 'restraint', text: 'Receive criticism without explanation or defense', difficulty: 'earnest' },
      { id: 'd_rst_8', category: 'restraint', text: 'Keep a significant accomplishment completely private', difficulty: 'earnest' },
      { id: 'd_rst_9', category: 'restraint', text: 'Allow yourself to be misunderstood for a week', difficulty: 'earnest' },
      { id: 'd_rst_10', category: 'restraint', text: 'Resist all forms of subtle bragging for three days', difficulty: 'earnest' },

      // DISCIPLINE - Devoted (10 missions)
      { id: 'd_dis_1', category: 'discipline', text: 'Maintain a practice you\'ve committed to, unseen', difficulty: 'earnest' },
      { id: 'd_dis_2', category: 'discipline', text: 'Study something difficult with no external reward', difficulty: 'earnest' },
      { id: 'd_dis_3', category: 'discipline', text: 'Fast from a significant comfort for three days', difficulty: 'earnest' },
      { id: 'd_dis_4', category: 'discipline', text: 'Wake at dawn for a week for private practice', difficulty: 'earnest' },
      { id: 'd_dis_5', category: 'discipline', text: 'Complete a challenging project telling no one', difficulty: 'earnest' },
      { id: 'd_dis_6', category: 'discipline', text: 'Maintain a difficult physical practice in secret', difficulty: 'earnest' },
      { id: 'd_dis_7', category: 'discipline', text: 'Abstain from all digital entertainment for a week', difficulty: 'earnest' },
      { id: 'd_dis_8', category: 'discipline', text: 'Master a skill through private daily practice', difficulty: 'earnest' },
      { id: 'd_dis_9', category: 'discipline', text: 'Keep a rigorous schedule without mentioning it', difficulty: 'earnest' },
      { id: 'd_dis_10', category: 'discipline', text: 'Train your body without tracking or sharing', difficulty: 'earnest' },

      // COURAGE - Devoted (10 missions)
      { id: 'd_crg_1', category: 'courage', text: 'Speak a difficult truth to someone in private', difficulty: 'earnest' },
      { id: 'd_crg_2', category: 'courage', text: 'Face a significant fear without telling anyone', difficulty: 'earnest' },
      { id: 'd_crg_3', category: 'courage', text: 'Stand alone for something you believe, quietly', difficulty: 'earnest' },
      { id: 'd_crg_4', category: 'courage', text: 'Make a hard decision without seeking validation', difficulty: 'earnest' },
      { id: 'd_crg_5', category: 'courage', text: 'End a relationship that no longer serves growth', difficulty: 'earnest' },
      { id: 'd_crg_6', category: 'courage', text: 'Confess something difficult without excusing it', difficulty: 'earnest' },
      { id: 'd_crg_7', category: 'courage', text: 'Challenge yourself significantly in private', difficulty: 'earnest' },
      { id: 'd_crg_8', category: 'courage', text: 'Do what\'s right when everyone disagrees', difficulty: 'earnest' },
      { id: 'd_crg_9', category: 'courage', text: 'Walk away from approval you could easily have', difficulty: 'earnest' },
      { id: 'd_crg_10', category: 'courage', text: 'Be vulnerable about a deep struggle, privately', difficulty: 'earnest' },

      // MERCY - Devoted (10 missions)
      { id: 'd_mrc_1', category: 'mercy', text: 'Forgive someone who doesn\'t know they need it', difficulty: 'earnest' },
      { id: 'd_mrc_2', category: 'mercy', text: 'Show extraordinary patience in a trying situation', difficulty: 'earnest' },
      { id: 'd_mrc_3', category: 'mercy', text: 'Release a justified resentment you\'ve held for years', difficulty: 'earnest' },
      { id: 'd_mrc_4', category: 'mercy', text: 'Extend grace when you have every right to anger', difficulty: 'earnest' },
      { id: 'd_mrc_5', category: 'mercy', text: 'Forgive yourself for something you\'ve carried for too long', difficulty: 'earnest' },
      { id: 'd_mrc_6', category: 'mercy', text: 'Choose compassion for someone who harmed you', difficulty: 'earnest' },
      { id: 'd_mrc_7', category: 'mercy', text: 'Let go of being right in a significant disagreement', difficulty: 'earnest' },
      { id: 'd_mrc_8', category: 'mercy', text: 'Think with genuine love about someone you dislike', difficulty: 'earnest' },
      { id: 'd_mrc_9', category: 'mercy', text: 'Give a second chance to someone who failed you', difficulty: 'earnest' },
      { id: 'd_mrc_10', category: 'mercy', text: 'Release all mental prosecution of someone who hurt you', difficulty: 'earnest' },

      // BENEVOLENCE - Devoted (10 missions)
      { id: 'd_bnv_1', category: 'benevolence', text: 'Give a significant financial gift anonymously', difficulty: 'earnest' },
      { id: 'd_bnv_2', category: 'benevolence', text: 'Sponsor someone\'s need without them knowing', difficulty: 'earnest' },
      { id: 'd_bnv_3', category: 'benevolence', text: 'Create lasting value for strangers in secret', difficulty: 'earnest' },
      { id: 'd_bnv_4', category: 'benevolence', text: 'Fund someone\'s dream without acknowledgment', difficulty: 'earnest' },
      { id: 'd_bnv_5', category: 'benevolence', text: 'Give away something precious anonymously', difficulty: 'earnest' },
      { id: 'd_bnv_6', category: 'benevolence', text: 'Pay a stranger\'s rent or bills secretly', difficulty: 'earnest' },
      { id: 'd_bnv_7', category: 'benevolence', text: 'Leave a transformative gift for someone to find', difficulty: 'earnest' },
      { id: 'd_bnv_8', category: 'benevolence', text: 'Support an artist or creator without their knowledge', difficulty: 'earnest' },
      { id: 'd_bnv_9', category: 'benevolence', text: 'Fully fund something needed by your community', difficulty: 'earnest' },
      { id: 'd_bnv_10', category: 'benevolence', text: 'Give sacrificially without anyone knowing', difficulty: 'earnest' }
    ]
  },

  steadfast: {
    name: 'Unseen Depths',
    unlocked: false,
    requiredActs: 30,
    missions: [
      // SERVICE - Steadfast (15 missions)
      { id: 's_svc_1', category: 'service', text: 'Serve someone daily for a month without mention', difficulty: 'solemn' },
      { id: 's_svc_2', category: 'service', text: 'Build something lasting for strangers anonymously', difficulty: 'solemn' },
      { id: 's_svc_3', category: 'service', text: 'Dedicate years to a cause no one will credit you for', difficulty: 'solemn' },
      { id: 's_svc_4', category: 'service', text: 'Sacrifice a major opportunity to serve another', difficulty: 'solemn' },
      { id: 's_svc_5', category: 'service', text: 'Create systemic change without seeking recognition', difficulty: 'solemn' },
      { id: 's_svc_6', category: 'service', text: 'Give your life\'s work away freely', difficulty: 'solemn' },
      { id: 's_svc_7', category: 'service', text: 'Serve those who can never repay you', difficulty: 'solemn' },
      { id: 's_svc_8', category: 'service', text: 'Labor in obscurity for the benefit of many', difficulty: 'solemn' },
      { id: 's_svc_9', category: 'service', text: 'Maintain essential work that no one notices', difficulty: 'solemn' },
      { id: 's_svc_10', category: 'service', text: 'Become a foundation others build upon unknowingly', difficulty: 'solemn' },
      { id: 's_svc_11', category: 'service', text: 'Preserve something beautiful for those who come after', difficulty: 'solemn' },
      { id: 's_svc_12', category: 'service', text: 'Plant trees whose shade you\'ll never enjoy', difficulty: 'solemn' },
      { id: 's_svc_13', category: 'service', text: 'Teach someone to surpass you, in shadow', difficulty: 'solemn' },
      { id: 's_svc_14', category: 'service', text: 'Quietly ensure others\' success at cost to yourself', difficulty: 'solemn' },
      { id: 's_svc_15', category: 'service', text: 'Become the unseen scaffold for someone\'s ascent', difficulty: 'solemn' },

      // RESTRAINT - Steadfast (15 missions)
      { id: 's_rst_1', category: 'restraint', text: 'Decline praise you could have accepted', difficulty: 'solemn' },
      { id: 's_rst_2', category: 'restraint', text: 'Let your best work be attributed to another', difficulty: 'solemn' },
      { id: 's_rst_3', category: 'restraint', text: 'Never speak of your greatest accomplishment', difficulty: 'solemn' },
      { id: 's_rst_4', category: 'restraint', text: 'Remain silent when your name is slandered', difficulty: 'solemn' },
      { id: 's_rst_5', category: 'restraint', text: 'Accept diminishment without complaint', difficulty: 'solemn' },
      { id: 's_rst_6', category: 'restraint', text: 'Keep your wisdom to yourself when others need to learn', difficulty: 'solemn' },
      { id: 's_rst_7', category: 'restraint', text: 'Watch your contribution be forgotten without correction', difficulty: 'solemn' },
      { id: 's_rst_8', category: 'restraint', text: 'Let go of the need to be understood', difficulty: 'solemn' },
      { id: 's_rst_9', category: 'restraint', text: 'Embrace obscurity when fame was available', difficulty: 'solemn' },
      { id: 's_rst_10', category: 'restraint', text: 'Refuse to justify yourself to anyone', difficulty: 'solemn' },
      { id: 's_rst_11', category: 'restraint', text: 'Accept being unknown for what you\'ve done', difficulty: 'solemn' },
      { id: 's_rst_12', category: 'restraint', text: 'Bear misunderstanding as a way of life', difficulty: 'solemn' },
      { id: 's_rst_13', category: 'restraint', text: 'Never defend your character or legacy', difficulty: 'solemn' },
      { id: 's_rst_14', category: 'restraint', text: 'Let your life speak without your voice', difficulty: 'solemn' },
      { id: 's_rst_15', category: 'restraint', text: 'Become invisible while remaining indispensable', difficulty: 'solemn' },

      // DISCIPLINE - Steadfast (15 missions)
      { id: 's_dis_1', category: 'discipline', text: 'Study something difficult for no external reward', difficulty: 'solemn' },
      { id: 's_dis_2', category: 'discipline', text: 'Maintain a daily practice for years in secret', difficulty: 'solemn' },
      { id: 's_dis_3', category: 'discipline', text: 'Master your craft without sharing your progress', difficulty: 'solemn' },
      { id: 's_dis_4', category: 'discipline', text: 'Train yourself rigorously without audience', difficulty: 'solemn' },
      { id: 's_dis_5', category: 'discipline', text: 'Fast from comfort for an extended period silently', difficulty: 'solemn' },
      { id: 's_dis_6', category: 'discipline', text: 'Build character through private hardship', difficulty: 'solemn' },
      { id: 's_dis_7', category: 'discipline', text: 'Pursue excellence known only to yourself', difficulty: 'solemn' },
      { id: 's_dis_8', category: 'discipline', text: 'Develop a skill to mastery without mentioning it', difficulty: 'solemn' },
      { id: 's_dis_9', category: 'discipline', text: 'Endure difficulty with grace and no complaint', difficulty: 'solemn' },
      { id: 's_dis_10', category: 'discipline', text: 'Cultivate virtue through unseen striving', difficulty: 'solemn' },
      { id: 's_dis_11', category: 'discipline', text: 'Forge yourself in the fire of anonymous struggle', difficulty: 'solemn' },
      { id: 's_dis_12', category: 'discipline', text: 'Choose the harder path repeatedly without witness', difficulty: 'solemn' },
      { id: 's_dis_13', category: 'discipline', text: 'Become who you must be in the dark', difficulty: 'solemn' },
      { id: 's_dis_14', category: 'discipline', text: 'Labor toward perfection no one will see', difficulty: 'solemn' },
      { id: 's_dis_15', category: 'discipline', text: 'Refine your soul through hidden devotion', difficulty: 'solemn' },

      // COURAGE - Steadfast (15 missions)
      { id: 's_crg_1', category: 'courage', text: 'Stand alone for something you believe, quietly', difficulty: 'solemn' },
      { id: 's_crg_2', category: 'courage', text: 'Risk everything for truth without fanfare', difficulty: 'solemn' },
      { id: 's_crg_3', category: 'courage', text: 'Face your deepest fear in complete solitude', difficulty: 'solemn' },
      { id: 's_crg_4', category: 'courage', text: 'Choose integrity over success silently', difficulty: 'solemn' },
      { id: 's_crg_5', category: 'courage', text: 'Walk away from everything for what\'s right', difficulty: 'solemn' },
      { id: 's_crg_6', category: 'courage', text: 'Endure persecution without seeking sympathy', difficulty: 'solemn' },
      { id: 's_crg_7', category: 'courage', text: 'Make the costly choice again and again in private', difficulty: 'solemn' },
      { id: 's_crg_8', category: 'courage', text: 'Remain faithful when all others abandon the cause', difficulty: 'solemn' },
      { id: 's_crg_9', category: 'courage', text: 'Bear witness to truth regardless of consequence', difficulty: 'solemn' },
      { id: 's_crg_10', category: 'courage', text: 'Die to yourself daily without mention', difficulty: 'solemn' },
      { id: 's_crg_11', category: 'courage', text: 'Confront evil with only conscience as witness', difficulty: 'solemn' },
      { id: 's_crg_12', category: 'courage', text: 'Sacrifice your dreams for another\'s good', difficulty: 'solemn' },
      { id: 's_crg_13', category: 'courage', text: 'Choose vulnerability without safety net', difficulty: 'solemn' },
      { id: 's_crg_14', category: 'courage', text: 'Become who you\'re meant to be despite all voices', difficulty: 'solemn' },
      { id: 's_crg_15', category: 'courage', text: 'Live your deepest truth in complete obscurity', difficulty: 'solemn' },

      // MERCY - Steadfast (15 missions)
      { id: 's_mrc_1', category: 'mercy', text: 'Offer grace to someone who wronged you deeply', difficulty: 'solemn' },
      { id: 's_mrc_2', category: 'mercy', text: 'Forgive the unforgivable without anyone knowing', difficulty: 'solemn' },
      { id: 's_mrc_3', category: 'mercy', text: 'Love your enemy in secret acts', difficulty: 'solemn' },
      { id: 's_mrc_4', category: 'mercy', text: 'Show compassion where none is deserved', difficulty: 'solemn' },
      { id: 's_mrc_5', category: 'mercy', text: 'Release all bitterness toward those who destroyed you', difficulty: 'solemn' },
      { id: 's_mrc_6', category: 'mercy', text: 'Bear someone\'s suffering as if it were your own', difficulty: 'solemn' },
      { id: 's_mrc_7', category: 'mercy', text: 'Forgive yourself for your deepest shame', difficulty: 'solemn' },
      { id: 's_mrc_8', category: 'mercy', text: 'Extend mercy when justice would be righteous', difficulty: 'solemn' },
      { id: 's_mrc_9', category: 'mercy', text: 'Choose love over vindication permanently', difficulty: 'solemn' },
      { id: 's_mrc_10', category: 'mercy', text: 'Absorb harm without returning it', difficulty: 'solemn' },
      { id: 's_mrc_11', category: 'mercy', text: 'Transform your pain into compassion for others', difficulty: 'solemn' },
      { id: 's_mrc_12', category: 'mercy', text: 'Become a wellspring of grace without recognition', difficulty: 'solemn' },
      { id: 's_mrc_13', category: 'mercy', text: 'Let mercy flow through you like a hidden river', difficulty: 'solemn' },
      { id: 's_mrc_14', category: 'mercy', text: 'Heal wounds by bearing them silently', difficulty: 'solemn' },
      { id: 's_mrc_15', category: 'mercy', text: 'Become mercy itself, unnamed and unnoticed', difficulty: 'solemn' },

      // BENEVOLENCE - Steadfast (15 missions)
      { id: 's_bnv_1', category: 'benevolence', text: 'Give away something you treasure anonymously', difficulty: 'solemn' },
      { id: 's_bnv_2', category: 'benevolence', text: 'Change someone\'s life financially without credit', difficulty: 'solemn' },
      { id: 's_bnv_3', category: 'benevolence', text: 'Fund a stranger\'s education in secret', difficulty: 'solemn' },
      { id: 's_bnv_4', category: 'benevolence', text: 'Give sacrificially until it costs you comfort', difficulty: 'solemn' },
      { id: 's_bnv_5', category: 'benevolence', text: 'Create an ongoing legacy of anonymous giving', difficulty: 'solemn' },
      { id: 's_bnv_6', category: 'benevolence', text: 'Provide for someone\'s basic needs indefinitely in shadow', difficulty: 'solemn' },
      { id: 's_bnv_7', category: 'benevolence', text: 'Become a secret patron to those in need', difficulty: 'solemn' },
      { id: 's_bnv_8', category: 'benevolence', text: 'Give your inheritance away without mention', difficulty: 'solemn' },
      { id: 's_bnv_9', category: 'benevolence', text: 'Live below your means to give radically in secret', difficulty: 'solemn' },
      { id: 's_bnv_10', category: 'benevolence', text: 'Make generosity your life\'s hidden purpose', difficulty: 'solemn' },
      { id: 's_bnv_11', category: 'benevolence', text: 'Establish systems of giving that outlive you', difficulty: 'solemn' },
      { id: 's_bnv_12', category: 'benevolence', text: 'Give everything you have for others\' flourishing', difficulty: 'solemn' },
      { id: 's_bnv_13', category: 'benevolence', text: 'Become an invisible force for good in many lives', difficulty: 'solemn' },
      { id: 's_bnv_14', category: 'benevolence', text: 'Let your wealth flow to others like water', difficulty: 'solemn' },
      { id: 's_bnv_15', category: 'benevolence', text: 'Die having given all away in secret', difficulty: 'solemn' }
    ]
  }
};
